name: KBOT-CICD

on: push
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
# перший крок задачі дозволить запускати на ранері репозиторій із скриптами для виконання дії. 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
# наступним кроком запустимо команду make test, зробимо коміт та подивимось як це працює
      - name: Run test
        run: make test
        
# авторизація на GHCR

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3        
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build&Push
        env:
          APP: "telebot"
        run: make image push TARGETARCH=$TARGETARCH
      - name: Clean
        run: make clean TARGETARCH=$TARGETARCH

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push
        
